name: Node App CI/CD GitOps Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/node-app

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Version
        run: echo "IMAGE_VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_VERSION .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_VERSION

      - name: Show Images
        run: docker images
